# Generated by Django 2.1.3 on 2018-11-22 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(default='Kendrick', help_text='First name', max_length=50)),
                ('user_lname', models.CharField(default='Lamar', help_text='Last name', max_length=50)),
                ('user_unique_email', models.CharField(default='Tupac@gmail.com', max_length=100)),
                ('user_password', models.CharField(default='abc123', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='publicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_fname', models.CharField(default='Biggie', help_text='First name', max_length=50)),
                ('public_lname', models.CharField(default='Smalls', help_text='Last name', max_length=50)),
                ('public_displayname', models.CharField(default='Tupac', help_text='Display name', max_length=30)),
                ('public_email', models.CharField(default='Tupac@gmail.com', help_text='Email', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_like_count', models.IntegerField()),
                ('review_star_count', models.IntegerField()),
                ('review_text', models.TextField(default='Macklemore is amazeballs', help_text='Type a review')),
                ('review_date_posted', models.DateField(default='1/1/18')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default="Tupac's 3-Pack Sodas", max_length=200)),
                ('public_displayname', models.CharField(default='Tupac', help_text='Display name', max_length=30)),
                ('service_cost', models.IntegerField()),
                ('service_category', models.CharField(default='J Cole', max_length=200)),
                ('service_location', models.CharField(default='Grandmaster Flash', max_length=200)),
                ('service_proficiency', models.IntegerField()),
                ('service_reviews', models.TextField(help_text='Type a review.')),
                ('skill_info', models.CharField(default='I am very skilled!', help_text='Tell us more about your skill!', max_length=1000)),
                ('skill', models.CharField(choices=[('Computers', 'Computers'), ('Music', 'Music'), ('Art', 'Art'), ('Sports', 'Sports'), ('Manual Labor', 'Manual Labor'), ('Tutoring', 'Tutoring')], default='Computers', max_length=50)),
                ('location', models.CharField(choices=[('UMass Amherst', 'UMass Amherst'), ('5-College', '5-College'), ('Off Campus', 'Off Campus')], default='1', max_length=50)),
                ('availability', models.CharField(choices=[('M', 'M'), ('T', 'T'), ('W', 'W'), ('Th', 'Th'), ('F', 'F'), ('Sat', 'Sat'), ('Sun', 'Sun'), ('Unavailable', 'Unavailable')], default='8', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='UserInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sidehustles.publicProfile')),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sidehustles.Services'),
        ),
    ]
