# Generated by Django 2.1.1 on 2018-10-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidehustles', '0002_auto_20181030_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='appUser',
        ),
    ]
