# Generated by Django 2.1.1 on 2018-11-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidehustles', '0003_auto_20181030_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofile',
            name='skill',
            field=models.CharField(choices=[('1', 'M'), ('2', 'T'), ('3', 'W'), ('4', 'Th'), ('5', 'F'), ('6', 'Sat'), ('7', 'Sun'), ('8', 'Unavailable')], default='8', max_length=9),
        ),
    ]
