# Generated by Django 2.1.3 on 2018-11-06 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sidehustles', '0005_auto_20181106_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='skill_info',
        ),
        migrations.AddField(
            model_name='services',
            name='availability',
            field=models.CharField(choices=[('M', 'M'), ('T', 'T'), ('W', 'W'), ('Th', 'Th'), ('F', 'F'), ('Sat', 'Sat'), ('Sun', 'Sun'), ('Unavailable', 'Unavailable')], default='8', max_length=9),
        ),
        migrations.AddField(
            model_name='services',
            name='location',
            field=models.CharField(choices=[('UMass Amherst', 'UMass Amherst'), ('5-College', '5-College'), ('Off Campus', 'Off Campus')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='skill',
            field=models.CharField(choices=[('Computers', 'Computers'), ('Music', 'Music'), ('Art', 'Art'), ('Sports', 'Sports'), ('Manual Labor', 'Manual Labor'), ('Tutoring', 'Tutoring')], default='Computers', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='skill_info',
            field=models.CharField(default='I am very skilled!', help_text='Tell us more about your skill!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
